insert into department(id,name) values (1,'Backend')
insert into department(id,name) values (2,'Frontend')
insert into department(id,name) values (3,'QA/BA')
insert into department(id,name) values (4,'PMO')
insert into department(id,name) values (5,'DEVOPS')
insert into department(id,name) values (6,'Mobile')